apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: volume-persistant
          mountPath: "/pv"
          readOnly: true
  volumes:
    - name: volume-persistant
      persistentVolumeClaim:
        claimName: mon-pvc