apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ml-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-ml
  template:
    metadata:
      labels:
        app: app-ml
    spec:
      containers:
        - name: src-ml
          image: gamingrent-registry:54274/src-ml:0.0.1
          readinessProbe:
            httpGet:
              path: /__ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 14
          livenessProbe:
            httpGet:
              path: /__health
              port: 8080
            periodSeconds: 3
            failureThreshold: 3

