apiVersion: v1
kind: Pod
metadata:
  name: environnment-demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DATABASE_HOST
          value: postgresql://staging.domain.com
        - name: AUTH_DOMAIN
          value: https://staging.sso.domain.com
        - name: THREAD_POOL_SIZE
          value: "100"
        - name: SERVICE_API_KEY
          value: "1zx7rfnr9fne-e8fe3"